### ISSUE TITLE
Runtime error when running plugin

### ISSUE THREAD

**Issue by scottmetoyer** [archivesspace/instance_joiner#5]
I have installed the plugin following the provided instructions, but I get this error when running it:

```
RuntimeError in Jobs#show

Showing C:/inetpub/wwwroot/plugins/instance_joiner/frontend/views/jobs/show.html.erb where line #28 raised:

No such template: "instance_joiner_job"
Extracted source (around line #28):

25:         <% end %>
26: 
27:         <%= readonly.emit_template "job_status", @job %>
28:         <%= readonly.emit_template "job", @job %>
29: 
30:         <% unless @files.empty? %>
31:           <section id="files" class="subrecord-form-dummy" >
Rails.root: C:/inetpub/wwwroot/data/tmp/jetty-0.0.0.0-8080-frontend.war-_-any-/webapp/WEB-INF

Application Trace | Framework Trace | Full Trace
app/helpers/aspace_form_helper.rb:351:in `emit_template'
app/views/jobs/_show_templates.html.erb:48:in `_app_views_jobs__show_templates_html_erb___251568807_16616'
app/helpers/aspace_form_helper.rb:356:in `emit_template'
app/helpers/aspace_form_helper.rb:752:in `readonly_context'
Request

Parameters:

{"id"=>"115"}
Show session dump

Show env dump

Response

Headers:

None
```

Any ideas what I'm doing wrong?

**Comment by cdibella** [comment]
@scottmetoyer - this plugin was developed to help with a very specific issue people needed to be remedied prior to an upgrade to 1.5.0 if they had imported EADs into a few of the earlier ArchivesSpace versions, which may mean it was not upgraded for later versions of ArchivesSpace. What version of ArchivesSpace are you using it with, and do you have a specific issue or issues that you're hoping to resolve by using it?

**Comment by ngeraci** [comment]
@cdibella - I work with @scottmetoyer and can give a little more background-- we got this error when trying to use the plugin in 1.5.4. 

We're in the process of upgrading from 1.4.2 to 1.5.4. When we upgraded our test instance to 1.5.4, we noticed that some collections had both boxes and folders showing up as top containers, when folders contained item objects, and hoped to resolve this issue with the plugin.

**Comment by cdibella** [comment]
@ngeraci - ah, that makes sense. In your 1.4.2 ArchivesSpace, do you have two instances for each of these, one for the box and one for the folder, rather than one instance that has the box as a Container 1 and the folder as a Container 2 (and the item as a Container three, since it sounds like you've got three levels). If so, that's what this is intended to fix, but you need to run it (by repository) in your 1.4.2 installation, not your 1.5.4 one. Then do the container conversion by upgrading to 1.5.4.

(If you're already running it in your 1.4.2 installation, try disabling any other plugins before running this. Sometimes the issue is there's another plugin there that this one isn't expecting.)

**Comment by ngeraci** [comment]
@cdibella thanks for clarifying! We were trying to run it in 1.5.4.

I'll have to take a closer look at the instances in 1.4.2 to make sure this is the right solution, and then run it there if so.

**Comment by davezuckerman** [comment]
@cdibella Any update on this. We've encountered the same problem (running version 1.4.1) 

We did try disabling other plugins but the problem persists.

Thanks!

**Comment by ngeraci** [comment]
@helliger we continued to encounter the problem after installing the plugin in 1.4.2. I think what we ended up doing was proceeding with the upgrade without using the plugin, and writing our own script to join container instances afterward.
